mysql -h${MYSQL_PORT_3306_TCP_ADDR} -p${MYSQL_ENV_MYSQL_ROOT_PASSWORD} -e "DROP DATABASE IF EXISTS ${DRUPAL_DB};" \
  && mysql -h${MYSQL_PORT_3306_TCP_ADDR} -p${MYSQL_ENV_MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE ${DRUPAL_DB};"
